# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 00:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner_balance', '0001_initial'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='transaction',
            index_together=set([('partner', 'date')]),
        ),
    ]
